# Generated by Django 4.1.1 on 2022-09-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_student_class_user_subsystem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='code',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
