# Generated by Django 4.1.1 on 2023-07-31 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chapter')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsystem.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='progression',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.progression'),
        ),
    ]
