# Generated by Django 4.1.1 on 2023-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competence',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competence',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progression',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
