# Generated by Django 4.1.1 on 2022-09-22 23:13

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/defaults/defaultuserprofile.svg', upload_to=account.utils.user_profile_path),
        ),
    ]
