# Generated by Django 4.1.1 on 2022-09-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[(0, 'student'), (1, 'parent'), (2, 'school'), (4, 'teacher'), (5, 'admin')], default='student', max_length=32),
        ),
    ]
