# Generated by Django 4.1.1 on 2023-07-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer_a', models.TextField(blank=True, null=True)),
                ('answer_b', models.TextField(blank=True, null=True)),
                ('answer_c', models.TextField(blank=True, null=True)),
                ('answer_d', models.TextField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=15, null=True)),
                ('seen_count', models.IntegerField(default=0)),
                ('answered_count', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(blank=True, max_length=15, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='studentquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentquestion',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentquestion',
            name='test',
        ),
        migrations.RemoveField(
            model_name='teacherassessment',
            name='subsystem',
        ),
        migrations.AddField(
            model_name='studentmark',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
