# Generated by Django 4.1.1 on 2022-09-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='description',
            field=models.CharField(default='goot', max_length=256),
            preserve_default=False,
        ),
    ]
