# Generated by Django 4.1.1 on 2023-07-26 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentquestion_assessmenttarget_studentanswer_and_more'),
        ('subsystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0001_initial'),
        ('profiles', '0002_alter_classteacher_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassessment',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.chapter'),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='competence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='complete_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='dateline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='question_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='taken_by',
            field=models.ManyToManyField(blank=True, related_name='taken_by', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='taken_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherassessment',
            name='assessment_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsystem.classroom'),
        ),
        migrations.AlterField(
            model_name='teacherassessment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='StudentQuestion',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmenttarget',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.teacherassessment'),
        ),
        migrations.AddField(
            model_name='assessmenttarget',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsystem.classroom'),
        ),
        migrations.AddField(
            model_name='assessmenttarget',
            name='target',
            field=models.ManyToManyField(blank=True, related_name='target', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='answered_by',
            field=models.ManyToManyField(blank=True, related_name='answered_by', to='profiles.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.teacherassessment'),
        ),
    ]
