# Generated by Django 4.1.1 on 2022-09-30 01:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmenttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
