# Generated by Django 4.1.5 on 2023-08-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassessment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherassessment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
