# Generated by Django 4.1.1 on 2022-10-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_first_name_alter_user_last_name'),
        ('assessment', '0006_alter_question_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacherprofile'),
        ),
    ]
