# Generated by Django 4.1.1 on 2022-10-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_alter_question_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='teacher',
        ),
    ]
