# Generated by Django 4.1.1 on 2022-10-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0018_alter_teacherassessment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassessment',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
