# Generated by Django 4.1.1 on 2022-10-02 09:39

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('subsystem', '0001_initial'),
        ('assessment', '0019_teacherassessment_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassessment',
            name='assessment_subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subsystem', chained_model_field='subsystem', null=True, on_delete=django.db.models.deletion.CASCADE, to='subsystem.subject'),
        ),
    ]
