# Generated by Django 4.1.1 on 2022-10-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0020_teacherassessment_assessment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
