# Generated by Django 4.1.1 on 2022-10-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_studentmark_percentage_studentmark_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
