# Generated by Django 4.1.1 on 2023-08-04 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_schoolprofile_cycle'),
        ('subsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subsystem',
        ),
        migrations.RemoveField(
            model_name='language',
            name='subsystem',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subsystem',
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_classroom', to='profiles.schoolprofile'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_subject', to='profiles.schoolprofile'),
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
