# Generated by Django 4.1.1 on 2023-08-04 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsystem', '0002_remove_classroom_cycle_remove_classroom_subsystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='subsystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subsystem.subsystem'),
        ),
    ]
