# Generated by Django 4.1.1 on 2023-08-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_studentguardian_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='cycle',
        ),
    ]
