# Generated by Django 4.1.1 on 2023-07-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_classteacher_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentguardian',
            name='relationship',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
