# Generated by Django 4.1.1 on 2023-08-04 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsystem', '0002_remove_classroom_cycle_remove_classroom_subsystem_and_more'),
        ('profiles', '0003_remove_schoolprofile_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school_language',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='subsysytem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subsystem.subsystem'),
        ),
    ]
