# Generated by Django 4.1.1 on 2023-08-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_schoolprofile_school_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='subsysytem',
            new_name='subsystem',
        ),
    ]
